---
engines:
  duplication:
    enabled: true
    config:
      languages:
        - javascript
    checks:
      Similar code:
        enabled: false
  # eslint:
  #   enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.js"
exclude_paths: ['test/*.js', './*.js']
