language: node_js
branches:
  only:
    - master

node_js:
   - "4"
   - "6"

install:
  - npm install
  - npm run build

before_script:
  - npm install -g codecov

after_success:
  - npm run coverage
  - codecov coverage/lcov.info

matrix:
  fast_finish: true

# container-base
sudo: false
